"""Regenerate the single root MASTER.md — table of contents + progress tracker.

Rebuilt from scratch every time from what's actually on disk (which recordings exist, which
have a notes file) rather than patched in place — simpler and can't drift out of sync.
"""

import datetime
from pathlib import Path

from .common import REPO_ROOT, cache_dir, notes_dir, read_json
from .discover import find_recordings

HEADER = """# MBA Sem-2 — Lecture Notes

_Auto-generated by `codes/process_lecture.py` — table rows are rebuilt from disk on every run, don't hand-edit them._

"""


def _duration_str(subject: str, video_path: Path) -> str:
    from .common import file_hash

    cache_path = cache_dir(subject) / "transcripts" / f"{file_hash(video_path)}.json"
    data = read_json(cache_path)
    if not data or not data.get("segments"):
        return "—"
    last_end = data["segments"][-1]["end"]
    return f"{int(last_end // 60)}m"


def rebuild_master(config: dict) -> None:
    lines = [HEADER]
    for subject in config["subjects"]:
        recordings = find_recordings(subject)
        n_dir = notes_dir(subject)
        done = 0
        rows = []
        for r in recordings:
            notes_path = n_dir / f"{r.slug}.md"
            is_done = notes_path.exists()
            done += is_done
            status = "✅ Done" if is_done else "⏳ Pending"
            notes_link = f"[Notes]({subject}/Notes/{r.slug}.md)" if is_done else "—"
            duration = _duration_str(subject, r.path) if is_done else "—"
            rows.append(f"| {r.lecture_num:02d} | {r.title} | {r.date_str} | {duration} | {status} | {notes_link} |")

        lines.append(f"## {subject} ({done}/{len(recordings)} done)\n")
        if rows:
            lines.append("| # | Lecture | Date | Duration | Status | Notes |")
            lines.append("|---|---|---|---|---|---|")
            lines.extend(rows)
        else:
            lines.append("_No recordings found yet under `shared/Recordings/`._")
        lines.append("")

    lines.append(f"_Last rebuilt: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}_\n")

    master_path = REPO_ROOT / config["paths"]["master_file"]
    master_path.write_text("\n".join(lines))
    print(f"[master] rebuilt {master_path}")
